// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiyimtuvaweudfhtjyan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpeWltdHV2YXdldWRmaHRqeWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDYwNDgsImV4cCI6MjA1OTg4MjA0OH0.NWKxswuqEn4e_NGtir4nG-MQSXcly9HmKDUh-iSBPh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);